# Generated by Django 3.2.15 on 2022-08-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='uploaded_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='file',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=0, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
