# Generated by Django 3.2.15 on 2022-08-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
