# Generated by Django 3.2.15 on 2022-08-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ManyToManyField(to='blog.Photo'),
        ),
    ]
