# Generated by Django 3.2.15 on 2022-08-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Photo'),
        ),
    ]
