# Generated by Django 3.2.15 on 2022-08-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-date'], 'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
    ]
