# Generated by Django 3.2.15 on 2022-08-25 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_photo_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='file',
        ),
    ]
