# Generated by Django 3.2.15 on 2022-08-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_image_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ManyToManyField(blank=True, to='blog.Photo'),
        ),
    ]
